export const USER_PROFILE_FETCH_REQUESTED = 'USER_PROFILE_FETCH_REQUESTED';
export const USER_PROFILE_FETCH_FAILED = 'USER_PROFILE_FETCH_FAILED';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';

export const USER_PROFILE_UPDATE_REQUESTED = 'USER_PROFILE_UPDATE_REQUESTED';
export const USER_PROFILE_UPDATE_FAILED = 'USER_PROFILE_UPDATE_FAILED';
export const USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED';
